import = [
    "~/.config/alacritty/colors/onedark.toml",
    "~/.config/alacritty/fonts/jetbrains_mono.toml"
    # "~/.config/alacritty/fonts/liberation_mono.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/fish"

[window]
padding = { y = 0 }
dynamic_padding = false
